# Generated by Django 2.0.3 on 2019-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='logo/')),
                ('icon', models.ImageField(blank=True, upload_to='logo/')),
                ('Status', models.BooleanField(default=True)),
                ('header_image', models.ImageField(blank=True, upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
